name: Build and Release Minesweeper Test

on:
  workflow_dispatch:
    
permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Get version from csproj
        id: get_version
        run: |
          # Extract version
          $version = (Select-Xml -Path ./Minesweeper/MineSweeper.csproj -XPath "//Version").Node.InnerText
          echo "version=$version" >> $env:GITHUB_OUTPUT


      - name: Publish app
        run: dotnet publish ./Minesweeper/MineSweeper.csproj -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true /p:IncludeAllContentForSelfExtract=true -o ./publish

      - name: Zip published app
        run: Compress-Archive -Path ./publish/* -DestinationPath Minesweeper-${{ steps.get_version.outputs.version }}.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          name: Minesweeper ${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false
          files: Minesweeper-${{ steps.get_version.outputs.version }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
